### ISSUE TITLE
Race condition in SCGI.py

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habitat#69]
`````` ======================================================================
FAIL: test_habitat.test_http.test_scgi.TestSCGIStartupShutdown.test_shutdown_tolerates_stuck_sockets
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/nose-0.11.4-py2.6.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/home/adam/Projects/habitat/tests/test_habitat/test_http/test_scgi.py", line 135, in test_shutdown_tolerates_stuck_sockets
    threading_checks.check_threads(live=0)
  File "/home/adam/Projects/habitat/tests/test_habitat/lib/threading_checks.py", line 35, in check_threads
    assert len(filter(lambda x: x.isAlive(), a)) == live
AssertionError: 
-------------------- >> begin captured logging << --------------------
habitat.http: ERROR: IOError while handling SCGI request
Traceback (most recent call last):
  File "/home/adam/Projects/habitat/habitat/http.py", line 257, in handle
    self.read_scgi_req()
  File "/home/adam/Projects/habitat/habitat/http.py", line 276, in read_scgi_req
    self.read_more()
  File "/home/adam/Projects/habitat/habitat/http.py", line 310, in read_more
    new_data = self.request.recv(4096)
timeout: timed out
--------------------- >> end captured logging << ---------------------```
``````

**Comment by adamgreig** [comment]
not any more!
